language: node_js
node_js: node

install:
  - npm i gitbook-cli
  - npm i gitbook-plugin-insert-logo

script:
  - ./node_modules/gitbook-cli/bin/gitbook.js build

deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh ""
    on:
      branch:
        - master

  - provider: script
    skip_cleanup: true
    script: bash deploy.sh $TRAVIS_BRANCH
    on:
      branch:
        - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
